import { FoodItem } from '../types/nutrition';

export const VERIFIED_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'food-chicken-breast',
    name: 'Grilled Chicken Breast',
    brand: 'TrackBite Whole Foods',
    servingSize: 150,
    servingUnit: 'g',
    calories: 247.5,
    proteinG: 46.5,
    carbsG: 0,
    fatG: 5.4,
    fiberG: 0,
    isVerified: true,
    category: 'protein',
  },
  {
    id: 'food-greek-yogurt',
    name: '0% Fat Plain Greek Yogurt',
    brand: 'Chobani',
    servingSize: 170,
    servingUnit: 'g',
    calories: 100,
    proteinG: 18,
    carbsG: 6,
    fatG: 0,
    fiberG: 0,
    isVerified: true,
    category: 'protein',
  },
  {
    id: 'food-oatmeal',
    name: 'Rolled Oats (Dry)',
    brand: 'Quaker',
    servingSize: 80,
    servingUnit: 'g',
    calories: 304,
    proteinG: 10.4,
    carbsG: 54.4,
    fatG: 5.6,
    fiberG: 8.2,
    isVerified: true,
    category: 'carbs',
  },
  {
    id: 'food-salmon',
    name: 'Wild Atlantic Salmon Fillet',
    brand: 'TrackBite Catch',
    servingSize: 180,
    servingUnit: 'g',
    calories: 374,
    proteinG: 36,
    carbsG: 0,
    fatG: 24,
    fiberG: 0,
    isVerified: true,
    category: 'protein',
  },
  {
    id: 'food-brown-rice',
    name: 'Steamed Brown Rice',
    brand: 'TrackBite Pantry',
    servingSize: 200,
    servingUnit: 'g',
    calories: 222,
    proteinG: 4.5,
    carbsG: 46,
    fatG: 1.6,
    fiberG: 3.5,
    isVerified: true,
    category: 'carbs',
  },
  {
    id: 'food-whey',
    name: '100% Gold Standard Whey Isolate',
    brand: 'Optimum Nutrition',
    servingSize: 31,
    servingUnit: 'g',
    calories: 120,
    proteinG: 24,
    carbsG: 3,
    fatG: 1,
    fiberG: 0,
    isVerified: true,
    category: 'protein',
  },
  {
    id: 'food-avocado',
    name: 'Fresh Hass Avocado',
    brand: 'Whole Foods',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    proteinG: 2,
    carbsG: 8.5,
    fatG: 14.7,
    fiberG: 6.7,
    isVerified: true,
    category: 'fats',
  },
  {
    id: 'food-eggs',
    name: 'Large Pasture-Raised Whole Eggs (2 eggs)',
    brand: 'Vital Farms',
    servingSize: 100,
    servingUnit: 'g',
    calories: 144,
    proteinG: 12.6,
    carbsG: 0.8,
    fatG: 9.9,
    fiberG: 0,
    isVerified: true,
    category: 'protein',
  },
  {
    id: 'food-sweet-potato',
    name: 'Baked Sweet Potato',
    brand: 'Organic Produce',
    servingSize: 200,
    servingUnit: 'g',
    calories: 180,
    proteinG: 4,
    carbsG: 41.4,
    fatG: 0.3,
    fiberG: 6.6,
    isVerified: true,
    category: 'carbs',
  },
  {
    id: 'food-almonds',
    name: 'Raw California Almonds',
    brand: 'Blue Diamond',
    servingSize: 30,
    servingUnit: 'g',
    calories: 173,
    proteinG: 6.4,
    carbsG: 6.1,
    fatG: 15,
    fiberG: 3.5,
    isVerified: true,
    category: 'fats',
  },
  {
    id: 'food-blueberries',
    name: 'Fresh Organic Blueberries',
    brand: 'Driscoll\'s',
    servingSize: 150,
    servingUnit: 'g',
    calories: 86,
    proteinG: 1.1,
    carbsG: 21.7,
    fatG: 0.5,
    fiberG: 3.6,
    isVerified: true,
    category: 'fruits_veg',
  },
  {
    id: 'food-spinach',
    name: 'Baby Spinach (Raw)',
    brand: 'Earthbound Farm',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    proteinG: 2.9,
    carbsG: 3.6,
    fatG: 0.4,
    fiberG: 2.2,
    isVerified: true,
    category: 'fruits_veg',
  },
];

export function searchFoodItems(query: string, category?: string): FoodItem[] {
  const cleanQ = query.trim().toLowerCase();
  return VERIFIED_FOOD_ITEMS.filter((item) => {
    const matchesQ = cleanQ === '' || item.name.toLowerCase().includes(cleanQ) || (item.brand && item.brand.toLowerCase().includes(cleanQ));
    const matchesCat = !category || category === 'all' || item.category === category;
    return matchesQ && matchesCat;
  });
}
